### PR TITLE
use make not toml for commands

### PR DESCRIPTION
**Pull request by rcy**
experiment to use Makefile rather than pndev.toml for repo commands from pndev

### CODE REVIEW

**Comment by rcy** [comment]
not sure how to run clippy locally... Followed README.md and ran

```
cargo clippy --all-targets --all-features -- -D warnings
error: no override and no default toolchain set
```

**Comment by ghedamat** [comment]
@rcy on the clippy error let's pair when we have a sec
I don't get it butit's likely because my rust setup is available also outside the nix shell..

**Review by ghedamat — APPROVED** [review]
@rcy this is great

as discussed I see what made you propose this change and I appreciate you pushing for it 

I updated the pr to resolve errors and support also pndev.toml in the meantime so that we can migrate slowly projects to  Makefile while also not having to require everyone to update pndev at once (see my comment on the matching PR)

lmk what you think!

**Comment by rcy** [comment]
bye

**Pull request closed without merging**
